### ISSUE TITLE
Exception in EB related to constrained/unconstrained CVT tracks

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#1060]
Most likely, almost surely, due to constrained and unconstrained track banks from CVT having different lengths sometimes.  A 1:1 mapping between those tracking banks' rows was the contract.

```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.jlab.clas.detector.DetectorData.getUTracksBank(DetectorData.java:407)
	at org.jlab.service.eb.EBEngine.processDataEvent(EBEngine.java:220)
	at org.jlab.service.eb.EBHBEngine.processDataEvent(EBHBEngine.java:22)
	at org.jlab.clas.reco.ReconstructionEngine.execute(ReconstructionEngine.java:376)
	at org.jlab.clara.sys.ServiceEngine.executeEngine(ServiceEngine.java:227)
	at org.jlab.clara.sys.ServiceEngine.execute(ServiceEngine.java:153)
	at org.jlab.clara.sys.Service.lambda$execute$2(Service.java:178)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by baltzell** [comment]
Apparently not a bug but user error in job configuration.
