### ISSUE TITLE
fix swimming problem leading to DCTB exceptions

### ISSUE THREAD

**Issue by raffaelladevita** [JeffersonLab/clas12-offline-software#505]
probably caused by swimming results being "null" 

2020-03-17 16:41:38.758: Error in 129.57.136.101%7960_java:clas12:DCTB (ID: 89824):
Error processing input event

java.lang.NullPointerException
	at org.jlab.rec.dc.track.TrackCandListFinder.setTrackPars(TrackCandListFinder.java:563)
	at org.jlab.service.dc.DCTBEngine.processDataEvent(DCTBEngine.java:235)
	at org.jlab.clas.reco.ReconstructionEngine.execute(ReconstructionEngine.java:264)
	at org.jlab.clara.sys.ServiceEngine.executeEngine(ServiceEngine.java:224)
	at org.jlab.clara.sys.ServiceEngine.execute(ServiceEngine.java:154)
	at org.jlab.clara.sys.Service.lambda$execute$2(Service.java:178)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zieglerv** [comment]
Added line of code to check against null tracks and trajectories.
