### ISSUE TITLE
Handle exception in DCTB

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12-offline-software#570]
java.lang.NullPointerException
	at org.jlab.rec.dc.track.TrackCandListFinder.setTrackPars(TrackCandListFinder.java:563)
	at org.jlab.service.dc.DCTBEngine.processDataEvent(DCTBEngine.java:235)
	at org.jlab.clas.reco.ReconstructionEngine.execute(ReconstructionEngine.java:264)
	at org.jlab.clara.sys.ServiceEngine.executeEngine(ServiceEngine.java:224)
	at org.jlab.clara.sys.ServiceEngine.execute(ServiceEngine.java:154)
	at org.jlab.clara.sys.Service.lambda$execute$2(Service.java:178)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by baltzell** [comment]
PR #583
