### ISSUE TITLE
Fix BAND service exceptions

### ISSUE THREAD

**Issue by raffaelladevita** [JeffersonLab/clas12-offline-software#594]
Error processing input event

java.lang.NullPointerException
	at org.jlab.rec.band.banks.RecoBankWriter.fillBandHitBanks(RecoBankWriter.java:48)
	at org.jlab.rec.band.banks.RecoBankWriter.appendBANDBanks(RecoBankWriter.java:129)
	at org.jlab.service.band.BANDEngine.processDataEvent(BANDEngine.java:57)
	at org.jlab.clas.reco.ReconstructionEngine.execute(ReconstructionEngine.java:264)
	at org.jlab.clara.sys.ServiceEngine.executeEngine(ServiceEngine.java:224)
	at org.jlab.clara.sys.ServiceEngine.execute(ServiceEngine.java:154)
	at org.jlab.clara.sys.Service.lambda$execute$2(Service.java:178)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by baltzell** [comment]
#622
